name: Sync on DOM Cloud
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {
              "features": [
                {"create": {"domain": "uptask-mvc-php-dwfs.sao.dom.my.id", "user": "uptask-mvc-php-dwfs", "pass": "<redacted>", "email": "gaboangel.co@gmail.com"}},
                "firewall", "php 8.3", "mysql", "ssl", "ssl always"
              ],
              "source": "https://github.com/gabrielangel283/UpTask-MVC-php-DWFS.git",
              "root": "public_html/public",
              "nginx": {
                "fastcgi": "on",
                "locations": [
                  {"match": "/", "try_files": "$uri $uri/ /index.php$is_args$args"},
                  {"match": "~ \\.[^\\/]+(?<!\\.php)$", "try_files": "$uri =404"}
                ]
              },
              "commands": [
                "echo \"DB_HOST=localhost\" > .env",
                "echo \"DB_USER=${USERNAME}\" >> .env",
                "echo \"DB_PASS=${PASSWORD}\" >> .env",
                "echo \"DB_NAME=${DATABASE}\" >> .env",
                "echo \"PROJECT_URL=https://uptask-mvc-php-dwfs.sao.dom.my.id\" >> .env",
                "composer install"
              ]
            }